on:
  pull_request:
    branches:
      - master
    types: [closed]
jobs:
  loadero-test:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
