name: Example CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  loadero-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          TEST_ID: ${{ secrets.TEST_ID }}
