name: Update Loadero tests in a project

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:
  pull_request:

jobs:
  check-changes:
    runs-on: ubuntu-latest

    outputs:
      test-configs: ${{ steps.filter.outputs.test-configs }}

    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          base: ${{ github.ref }}
          filters: |
            test-configs:
              - 'python/src/loadero_python_showcase/configs/**'
  
  update-tests:
    needs: check-changes
    if: ${{ needs.check-changes.outputs.test-configs == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: pip install loadero-python
      - name: "Update Loadero tests"
        run: |
          cd ./python/src/loadero_python_showcase
          python update_tests.py
        env:
          LOADERO_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          LOADERO_PROJECT_ID: ${{ secrets.PROJECT_ID }}